---
name: build-and-test

on:
  push:
    branches:
      - main
  pull_request:      

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Build
        run: make build
